---
- name: Add PPA for Postgres 9.2
  apt_repository: repo=ppa:pitti/postgresql

- name: Install postgresql
  apt: pkg=postgresql-9.2

- name: Install postgresql-contrib
  apt: pkg=postgresql-contrib-9.2

- name: Install libpq-dev
  apt: pkg=libpq-dev

- name: Install python-psycopg2
  apt: pkg=python-psycopg2

- name: Create user
  postgresql_user: name=postgres password=postgres 
  sudo_user: postgres

- name: Create database
  postgresql_db: name=my_db
  sudo_user: postgres
